dist: xenial
language: c++
compiler: clang
before_install:
  - sudo add-apt-repository ppa:mhier/libboost-latest -y
  - sudo apt-get update -q
install:
  - sudo apt-get install libboost1.70-dev -y
script:
  - gcc --version
  - g++ --version
  - cmake --version
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexandrbashkirev:$BINTRAY_API_KEY "https://api.bintray.com/content/alexandrbashkirev/otus_cpp/homeworks/$TRAVIS_BUILD_NUMBER/bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"